imports:
    - { resource: config.yml }

framework:
    profiler: { enabled: true }
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

# jackalope doctrine caching
liip_doctrine_cache:
    namespaces:
        meta:
            type: array
        nodes:
            type: array