imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata.yml }
    - { resource: cmf.yml }
    - { resource: fos.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v1 # Capifony updates this with the hash of the current release
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        path:     "%database_path%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

#    orm:
#        entity_managers:
#            default:
#                connection: default
#                auto_mapping: true

doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
            connection: doctrine.dbal.default_connection
            caches:
                meta: liip_doctrine_cache.ns.meta
                nodes: liip_doctrine_cache.ns.nodes
        workspace: default
        username: admin
        password: admin
    odm:
        auto_mapping: true
        mappings:
            SonataMediaBundle:
                prefix: Sonata\MediaBundle\PHPCR
        locales:
            en: ~
        image:
            imagine_filter: false

# jackalope doctrine caching
liip_doctrine_cache:
    namespaces:
        meta:
            type: file_system
#            type: apc
        nodes:
#            type: file_system
            type: apc

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#fos_user:
#    db_driver:     orm
#    firewall_name: main
#    user_class:    Ducos\RU\UserBundle\Entity\User
#
#    group:
#        group_class: Ducos\RU\UserBundle\Entity\Group
#
#    profile:  # Authentication Form
#        form:
#            type:               fos_user_profile
#            name:               fos_user_profile_form
#            validation_groups:  [Authentication] # Please note : this is not the default value